// ====== CONTENIDO SEMANAL (semanas 4–42) ======
// cm: longitud aproximada (CRL hasta la semana 19, talla completa desde la 20). g: peso aproximado.
const SEMANAS = [
{w:4,cm:0.1,g:null,cmp:"una semilla de amapola",
 bebe:["El embrión acaba de implantarse en el útero.","Empiezan a formarse las tres capas de las que saldrán todos los órganos.","Todavía es un grupo de células, pero ya está en marcha."],
 ella:"Puede que todavía no notes nada, o que sientas el pecho más sensible y algo de cansancio. El test suele dar positivo a partir de ahora.",
 pareja:"Este es el momento de decidir juntos con quién compartirlo y con quién no. Guarda la fecha del test positivo: es el primer recuerdo de esta historia.",
 hitos:"Test de embarazo positivo. Conviene pedir ya la primera consulta prenatal.",
 temas:["¿Queremos guardar este secreto un tiempo o contarlo ya?","¿Con qué profesional o centro queremos hacer el seguimiento?"]},
{w:5,cm:0.2,g:null,cmp:"una semilla de sésamo",
 bebe:["Se forma el tubo neural, el origen del cerebro y la médula espinal.","El corazón empieza a formarse y pronto latirá.","Aparece el saco vitelino, que lo alimenta hasta que la placenta funcione."],
 ella:"Es habitual el cansancio intenso, ir más al baño y cierta sensibilidad a los olores. Las náuseas pueden empezar en cualquier momento.",
 pareja:"Ocúpate de pedir la primera consulta prenatal y de tener a mano la fecha de la última menstruación: la van a pedir en cada cita.",
 hitos:"Primera consulta prenatal (entre la semana 6 y la 8). Ácido fólico si todavía no lo toma.",
 temas:["¿Cuándo queremos la primera consulta y quién va?","¿Hay algo de nuestra rutina que queramos cambiar desde ya?"]},
{w:6,cm:0.5,g:null,cmp:"una lenteja",
 bebe:["El corazón ya late, aunque a veces todavía no se ve en la ecografía.","Aparecen los brotes de brazos y piernas.","Se empiezan a formar ojos, oídos y nariz."],
 ella:"Puede que estés agotada aunque nada se note por fuera. Las náuseas y los vómitos son frecuentes; comer poco y a menudo suele ayudar.",
 pareja:"Aunque todavía no se note, puede estar extremadamente cansada. Hazte cargo de las comidas y de que haya siempre algo ligero para picar.",
 hitos:"Primera ecografía (entre la semana 6 y la 9): confirma que el embarazo es intrauterino y detecta actividad cardíaca.",
 temas:["¿Cómo queremos repartir las tareas de casa estas semanas?","¿Queremos ir juntos a la primera ecografía?"]},
{w:7,cm:1,g:null,cmp:"un arándano",
 bebe:["El cerebro crece muy rápido y ya se distinguen sus zonas.","Brazos y piernas se alargan; se insinúan las manos.","Se forman los riñones y el aparato digestivo."],
 ella:"Las náuseas suelen ser más intensas en esta etapa. El cansancio y los cambios de humor son normales: tu cuerpo está haciendo muchísimo trabajo.",
 pareja:"Pregúntale qué necesita en lugar de asumirlo. Un día puede querer compañía y al siguiente silencio y descanso. Las dos cosas están bien.",
 hitos:"Primera ecografía y primera analítica completa (grupo sanguíneo, serologías, hemograma).",
 temas:["¿Qué queremos preguntar en la primera consulta?","¿Cómo nos organizamos para que pueda descansar más?"]},
{w:8,cm:1.6,g:1,cmp:"una frambuesa",
 bebe:["Ya tiene dedos, todavía unidos por membranas.","Se mueve, aunque todavía no puedes sentirlo.","El corazón late a unos 150 latidos por minuto."],
 ella:"Los síntomas pueden estar en su punto más intenso: náuseas, cansancio, pechos doloridos, aversiones a comidas. Es una etapa dura y pasa.",
 pareja:"Los síntomas pueden empezar a sentirse más intensos. Pregúntale qué necesita, y ocúpate de la logística de la primera ecografía y la analítica.",
 hitos:"Primera ecografía: se mide el embrión (CRL) y se ajusta la fecha probable de parto si hace falta.",
 temas:["¿Queremos hacer el test prenatal no invasivo (NIPT)?","¿Cuándo le contamos a los abuelos?"]},
{w:9,cm:2.3,g:2,cmp:"una uva",
 bebe:["Deja de ser embrión y pasa a llamarse feto.","Los músculos empiezan a funcionar y se mueve más.","Se forman los párpados y los pabellones auditivos."],
 ella:"Puedes notar la ropa más ajustada por hinchazón, no todavía por el útero. Las náuseas pueden seguir; hidratarte bien importa más que nunca.",
 pareja:"Infórmate sobre el NIPT y las opciones de cribado: fechas, coste, dónde se hace. Que ella no tenga que investigarlo todo.",
 hitos:"Cribado del primer trimestre: se planifican el NIPT (desde la semana 10) y la ecografía de la semana 12.",
 temas:["¿Queremos saber el sexo cuando sea posible?","¿Qué cobertura médica tenemos y qué cubre del embarazo y el parto?"]},
{w:10,cm:3.1,g:4,cmp:"una fresa",
 bebe:["Los órganos principales ya están formados; ahora toca madurar.","Los dedos de manos y pies están más definidos.","Traga líquido amniótico y mueve brazos y piernas."],
 ella:"Es posible que esta semana estés más cansada. Algunas personas empiezan a notar alivio de las náuseas; otras todavía no. Ambas cosas son normales.",
 pareja:"Puedes encargarte de la logística del NIPT y de las próximas citas: reservar, confirmar, acompañar. Anota las preguntas que quieran hacer.",
 hitos:"Test prenatal no invasivo (NIPT): se puede hacer desde la semana 10 con una extracción de sangre.",
 temas:["¿Cuándo queremos contarle a la familia?","¿Dónde queremos que nazca?"]},
{w:11,cm:4.1,g:7,cmp:"un higo",
 bebe:["La cabeza ocupa casi la mitad del cuerpo; se va equilibrando.","Se forman las uñas y los folículos del pelo.","Ya se distinguen los genitales, aunque no se ven bien en la eco."],
 ella:"Puedes tener más apetito y algo más de energía. Los mareos al levantarte rápido son comunes; hazlo despacio.",
 pareja:"Coordina la ecografía del primer trimestre: fecha, hora, quién va. Es una cita importante y conviene ir los dos.",
 hitos:"Ecografía del primer trimestre entre la semana 11 y la 13+6 (translucencia nucal).",
 temas:["¿Qué esperamos de la ecografía de la semana 12?","¿Cómo queremos que sea nuestra vida social estos meses?"]},
{w:12,cm:5.4,g:14,cmp:"una ciruela",
 bebe:["Los reflejos aparecen: abre y cierra las manos y los dedos de los pies.","Los intestinos se recolocan dentro del abdomen.","La placenta ya se ocupa de alimentarlo."],
 ella:"Para muchas, las náuseas empiezan a aflojar. Puede que notes la piel diferente y algo de congestión nasal.",
 pareja:"La primera ecografía importante puede ser un momento emocionalmente intenso para ambos. Estar presente, sin prisa, es lo que cuenta.",
 hitos:"Ecografía del primer trimestre. Suele ser el momento de compartir la noticia con más gente.",
 temas:["¿A quién se lo contamos ahora y cómo?","¿Guardamos una foto o un audio de este momento?"]},
{w:13,cm:7.4,g:23,cmp:"un kiwi",
 bebe:["Tiene huellas dactilares únicas.","Las cuerdas vocales se están formando.","Empieza a producir orina y a expulsarla al líquido amniótico."],
 ella:"Termina el primer trimestre. Es frecuente sentirse mejor y con más energía, aunque no a todo el mundo le pasa a la vez.",
 pareja:"Revisa con ella qué cambió estas semanas y qué puede seguir necesitando. Que el alivio de los síntomas no signifique que todo vuelve a como antes.",
 hitos:"Cierre del cribado del primer trimestre.",
 temas:["¿Qué queremos organizar antes del segundo trimestre?","¿Cómo nos sentimos cada uno con lo vivido hasta ahora?"]},
{w:14,cm:8.7,g:43,cmp:"un limón",
 bebe:["Empieza el segundo trimestre.","Puede hacer muecas y chuparse el dedo.","Aparece el lanugo, un vello fino que lo cubre."],
 ella:"Es probable que tengas más energía y apetito. El útero empieza a asomar por encima del pubis.",
 pareja:"Es buen momento para planificar: licencia parental, cobertura médica, dónde nacerá. Hazte responsable de investigar una de estas cosas.",
 hitos:"Consulta de seguimiento del segundo trimestre.",
 temas:["¿Cómo queremos repartir la licencia parental?","¿Empezamos una lista de nombres?"]},
{w:15,cm:10.1,g:70,cmp:"una manzana",
 bebe:["Percibe la luz a través de los párpados cerrados.","Los huesos se endurecen y ya se ven en la ecografía.","Practica movimientos de respiración con el líquido amniótico."],
 ella:"Puedes notar la nariz congestionada y algo de sangrado de encías: es normal por el aumento de flujo sanguíneo.",
 pareja:"Si ya tienen fecha para la ecografía morfológica, ponla en el calendario de ambos. Investiga opciones de clases de preparación al parto.",
 hitos:"Algunos centros ofrecen ecografía intermedia entre la semana 14 y la 16.",
 temas:["¿Queremos hacer clases de preparación al parto juntos?","¿Cuándo empezamos a mirar cosas para el bebé?"]},
{w:16,cm:11.6,g:100,cmp:"un aguacate",
 bebe:["Los músculos de la espalda y el cuello se fortalecen: levanta la cabeza.","Puede oír sonidos sordos desde fuera.","Ya se puede ver el sexo en la ecografía, si quieren saberlo."],
 ella:"Puede que sientas los primeros movimientos, como burbujas o mariposas. Si no, es normal: muchas los notan más tarde.",
 pareja:"Habla con el bebé: empieza a oír. Y acuerda con ella cómo quieren enterarse del sexo, si es que quieren.",
 hitos:"Segunda analítica del embarazo en algunos protocolos.",
 temas:["¿Queremos saber el sexo? ¿Y contarlo?","¿Empezamos a pensar en la habitación?"]},
{w:17,cm:13,g:140,cmp:"una pera",
 bebe:["Empieza a acumular grasa, que le ayudará a regular la temperatura.","El cordón umbilical se fortalece y engrosa.","Su corazón ya late de forma regulada por el cerebro."],
 ella:"Puedes notar el centro de gravedad distinto y algo de dolor en la zona baja del vientre por el estiramiento de ligamentos.",
 pareja:"Ocúpate de la logística de la ecografía morfológica: es una de las citas más importantes y suele durar más que las anteriores.",
 hitos:"Preparación de la ecografía morfológica (semana 18–22).",
 temas:["¿Qué queremos preguntar en la eco morfológica?","¿Cómo queremos celebrar la mitad del embarazo?"]},
{w:18,cm:14.2,g:190,cmp:"un pimiento",
 bebe:["Los oídos ya están en su posición definitiva.","Bosteza, se estira y tiene ciclos de sueño.","Se recubre de vérnix, una capa protectora."],
 ella:"Los movimientos son cada vez más claros. Puede aparecer algo de dolor de espalda: cambiar de postura y descansar de lado ayuda.",
 pareja:"Es posible que pronto empiece a sentir movimientos. Pregúntale cuándo los nota y prueba a apoyar la mano: todavía puede ser pronto para ti.",
 hitos:"Ecografía morfológica entre la semana 18 y la 22.",
 temas:["¿Qué nombres nos gustan de verdad a los dos?","¿Cómo vamos con la lista de tareas compartidas?"]},
{w:19,cm:15.3,g:240,cmp:"un mango",
 bebe:["Se desarrollan las áreas sensoriales del cerebro: tacto, gusto, olfato.","Si es niña, ya tiene millones de óvulos formados.","Su piel se cubre de vérnix para protegerse del líquido."],
 ella:"Puedes tener calambres en las piernas, sobre todo de noche. Estirar antes de dormir y hidratarte ayuda.",
 pareja:"Coordina con ella las compras grandes (cochecito, cuna) sin comprarlas todavía: investiga, compara, propón.",
 hitos:"Ecografía morfológica.",
 temas:["¿Qué necesitamos de verdad para los primeros meses?","¿Queremos hacer una lista de regalos?"]},
{w:20,cm:25.6,g:300,cmp:"una banana",
 bebe:["Mitad del embarazo. A partir de ahora se mide de la cabeza a los pies.","Traga más líquido amniótico y su intestino produce meconio.","Sus movimientos son más coordinados."],
 ella:"El ombligo puede empezar a salir y el útero llega a la altura del ombligo. Es frecuente sentirse bien en esta etapa.",
 pareja:"La ecografía morfológica es uno de los grandes hitos del embarazo. Ve con ella, pregunta lo que no entiendas y guarden la imagen.",
 hitos:"Ecografía morfológica: revisión detallada de órganos, placenta y crecimiento.",
 temas:["¿Cómo nos sentimos después de la morfológica?","¿A quién falta contárselo?"]},
{w:21,cm:26.7,g:360,cmp:"una zanahoria",
 bebe:["Sus movimientos ya son patadas claras.","Las cejas y los párpados están completos.","Empieza a tener un patrón de actividad y descanso."],
 ella:"Puedes notar estrías y picor en la piel del vientre. Hidratarla alivia, aunque no las evita del todo.",
 pareja:"Apoya la mano cuando ella te avise de que se mueve. Esta semana o la que viene puede ser la primera vez que lo sientas.",
 hitos:null,
 temas:["¿Queremos hacer un viaje antes del tercer trimestre?","¿Cómo organizamos la habitación?"]},
{w:22,cm:27.8,g:430,cmp:"una papaya",
 bebe:["Ya tiene aspecto de recién nacido en miniatura.","Se distinguen labios y párpados; los ojos están formados pero sin color definitivo.","Sus movimientos pueden sentirse desde fuera."],
 ella:"Puedes tener los pies algo hinchados al final del día y más sed de lo habitual.",
 pareja:"Hazte responsable de revisar la cobertura médica del parto y los trámites de licencia. Tener eso resuelto quita presión a ambos.",
 hitos:"Consulta de seguimiento.",
 temas:["¿Qué tipo de parto nos gustaría, si todo va bien?","¿Quién queremos que esté en el hospital?"]},
{w:23,cm:28.9,g:500,cmp:"un pomelo",
 bebe:["El oído está maduro: reconoce tu voz y la de tu pareja.","Los pulmones empiezan a producir surfactante.","Su piel todavía es fina y arrugada."],
 ella:"Puedes notar contracciones de Braxton Hicks, suaves e irregulares. Son de práctica; si se vuelven regulares o dolorosas, consulta.",
 pareja:"Papá o pareja sintió la primera patada suele ocurrir por estas semanas. Guarda ese momento como recuerdo.",
 hitos:"Prueba de glucosa (O'Sullivan) entre la semana 24 y la 28.",
 temas:["¿Cómo queremos que sean las visitas cuando nazca?","¿Qué nos preocupa del parto?"]},
{w:24,cm:30,g:600,cmp:"una mazorca de maíz",
 bebe:["Sus pulmones desarrollan las ramificaciones que necesitará para respirar.","Se le forman las papilas gustativas.","Responde a sonidos fuertes con movimientos."],
 ella:"Es frecuente el dolor lumbar y la piel más sensible. Puede que el sueño empiece a costar más.",
 pareja:"Ocúpate de organizar la prueba de glucosa: hay que ir en ayunas y dura un rato. Acompáñala si puedes.",
 hitos:"Prueba de glucosa. Analítica del segundo trimestre.",
 temas:["¿Empezamos a preparar el bolso del hospital?","¿Cómo repartimos las noches cuando nazca?"]},
{w:25,cm:34.6,g:660,cmp:"una coliflor",
 bebe:["Su pelo tiene color y textura.","Empieza a ganar peso más rápido.","Sus manos son plenamente funcionales."],
 ella:"Puedes tener ardor de estómago: comer despacio y en cantidades pequeñas ayuda. Las hemorroides también son comunes.",
 pareja:"Investiga cursos de preparación al parto y de primeros cuidados. Apúntate tú también: no es un curso 'para ella'.",
 hitos:"Consulta de seguimiento.",
 temas:["¿Qué queremos aprender antes de que nazca?","¿Queremos contratar ayuda extra las primeras semanas?"]},
{w:26,cm:35.6,g:760,cmp:"una lechuga",
 bebe:["Abre los ojos por primera vez.","Sus ondas cerebrales ya son parecidas a las de un recién nacido.","Se sobresalta con ruidos y responde a la luz."],
 ella:"Puedes sentirte más torpe y con menos equilibrio. Cuida las posturas al levantarte y al agacharte.",
 pareja:"Revisen juntos los resultados de la glucosa y la analítica. Anota las dudas para la próxima cita.",
 hitos:"Resultados de glucosa y analítica del segundo trimestre.",
 temas:["¿Cómo queremos comunicar el nacimiento a la familia?","¿Qué nombres siguen en la lista?"]},
{w:27,cm:36.6,g:875,cmp:"una berenjena",
 bebe:["Termina el segundo trimestre.","Tiene hipo, y puede que lo notes como pequeños saltos rítmicos.","Su cerebro se desarrolla a gran velocidad."],
 ella:"Puedes tener sueños intensos, cansancio de nuevo y los pies más hinchados. Dormir de lado con una almohada entre las piernas ayuda.",
 pareja:"Empieza a tomar responsabilidad directa sobre la preparación práctica: habitación, compras, trámites. Ella no debería estar cargando cosas.",
 hitos:"Vacuna de la tosferina (semana 27–36) e inmunoglobulina anti-D si es Rh negativo (semana 28).",
 temas:["¿Qué falta comprar y qué puede esperar?","¿Queremos hacer un baby shower o algo parecido?"]},
{w:28,cm:37.6,g:1000,cmp:"un repollo",
 bebe:["Empieza el tercer trimestre. Ya pesa alrededor de un kilo.","Puede parpadear y soñar.","Suele girarse hacia abajo por estas semanas, aunque no siempre."],
 ella:"El útero presiona los pulmones: puedes tener la respiración más corta. Te van a proponer contar movimientos: si notas menos de lo habitual, consulta.",
 pareja:"Aprende las señales por las que hay que consultar: sangrado, contracciones regulares, menos movimientos, dolor de cabeza fuerte. Que no dependa solo de ella recordarlas.",
 hitos:"Inicio del tercer trimestre. Analítica del tercer trimestre y consulta con más frecuencia.",
 temas:["¿Cuál es nuestro plan si el parto se adelanta?","¿Cómo llegamos al hospital y quién nos cubre?"]},
{w:29,cm:38.6,g:1150,cmp:"una calabaza pequeña",
 bebe:["Sus huesos absorben calcio y se fortalecen.","Se mueve mucho, aunque tiene menos espacio.","Regula mejor su temperatura."],
 ella:"El cansancio vuelve y el sueño se interrumpe. Descansa cuando puedas, aunque sea a ratos.",
 pareja:"Ocúpate de las compras pesadas y del montaje de muebles. Y pregúntale cómo se siente, no solo cómo va el bebé.",
 hitos:"Consulta de seguimiento (cada 2–3 semanas a partir de ahora).",
 temas:["¿Qué queremos del posparto?","¿Quién nos gustaría que nos acompañe las primeras semanas?"]},
{w:30,cm:39.9,g:1320,cmp:"un melón",
 bebe:["Su piel se alisa y el lanugo empieza a caerse.","Su médula ósea produce glóbulos rojos.","Distingue entre luz y oscuridad."],
 ella:"Puedes tener acidez, calambres y ganas de orinar constantes. Es una etapa pesada; cuida el descanso y las posturas.",
 pareja:"Empieza a tomar responsabilidad directa sobre la preparación práctica: bolso, silla del coche, habitación. Hazte una lista y ve tachando.",
 hitos:"Ecografía del tercer trimestre (semana 32–36) en muchos protocolos.",
 temas:["¿Cómo será la vuelta a casa desde el hospital?","¿Qué nos gustaría que no nos falte los primeros días?"]},
{w:31,cm:41.1,g:1500,cmp:"un coco",
 bebe:["Sus cinco sentidos funcionan.","Gira la cabeza y mueve los ojos.","Acumula grasa y se le redondea el cuerpo."],
 ella:"Puedes notar pérdidas de calostro y dolor en las costillas por la presión del útero.",
 pareja:"Instala y aprende a usar la silla del coche. Es una de las pocas cosas que se necesita sí o sí desde el primer día.",
 hitos:null,
 temas:["¿Qué queremos decidir sobre lactancia?","¿Cómo repartimos las noches al principio?"]},
{w:32,cm:42.4,g:1700,cmp:"una calabaza",
 bebe:["Practica la respiración con movimientos rítmicos.","Sus uñas llegan a la punta de los dedos.","Casi todos los órganos están maduros, salvo los pulmones."],
 ella:"Puedes tener más contracciones de Braxton Hicks y sentir el bebé bajo en la pelvis. Si las contracciones son regulares, consulta.",
 pareja:"Coordina con ella las visitas al hospital o maternidad: conocer el lugar reduce nervios el día del parto.",
 hitos:"Ecografía del tercer trimestre: posición del bebé, crecimiento y líquido amniótico.",
 temas:["¿Hemos visitado el hospital o la maternidad?","¿Cómo queremos que sea el momento de anunciar que nació?"]},
{w:33,cm:43.7,g:1900,cmp:"una piña",
 bebe:["Los huesos del cráneo siguen blandos para atravesar el canal del parto.","Su sistema inmunitario recibe anticuerpos de la madre.","Duerme y sueña buena parte del día."],
 ella:"Puedes tener hormigueo en las manos y dificultad para encontrar una postura cómoda. Camina y cambia de posición a menudo.",
 pareja:"Ten el coche revisado y sabe el camino al hospital. Guarda los números importantes en tu teléfono: centro, matrona o partera, familia.",
 hitos:"Consulta de seguimiento.",
 temas:["¿Qué queremos en el plan de parto?","¿Qué hacemos si llega antes de lo previsto?"]},
{w:34,cm:45,g:2100,cmp:"un melón grande",
 bebe:["Los pulmones están casi maduros.","Las uñas de las manos ya están completas.","Sus movimientos son más lentos pero fuertes."],
 ella:"El sueño se fragmenta y la pelvis puede doler. Puedes sentirte ansiosa por el parto: hablarlo ayuda.",
 pareja:"Preparen el bolso del hospital juntos. Tu parte: tu ropa, cargadores, documentación de ambos, snacks.",
 hitos:"Preparación del bolso del hospital. Cultivo de estreptococo del grupo B (semana 35–37).",
 temas:["¿Qué llevamos al hospital?","¿Quién avisa a la familia y cuándo?"]},
{w:35,cm:46.2,g:2400,cmp:"un melón de miel",
 bebe:["Gana entre 200 y 250 gramos por semana.","Los riñones están desarrollados y el hígado procesa desechos.","Casi no le queda espacio para dar volteretas."],
 ella:"Puedes notar que el bebé baja y respirar mejor, pero orinar aún más a menudo.",
 pareja:"Revisa con ella el plan de parto y confirma que lo conoce el equipo médico. Sabe qué quiere ella y cómo defenderlo si hace falta.",
 hitos:"Cultivo de estreptococo del grupo B. Consulta semanal a partir de ahora en muchos protocolos.",
 temas:["¿Qué queremos y qué no queremos en el parto?","¿Quién se ocupa de casa y mascotas cuando estemos en el hospital?"]},
{w:36,cm:47.4,g:2600,cmp:"una papaya grande",
 bebe:["El vérnix y el lanugo se van desprendiendo.","Sus encías son firmes y los músculos de succión están listos.","Suele estar ya en posición cefálica, cabeza abajo."],
 ella:"Puedes tener más presión en la pelvis y menos apetito. Pequeñas comidas frecuentes ayudan.",
 pareja:"Revisen juntos el plan para el parto: señales de que empieza, cuándo salir de casa, qué llevar, a quién avisar. Ensáyenlo una vez.",
 hitos:"Consulta de la semana 36: posición del bebé y planificación del parto.",
 temas:["¿Cuándo salimos hacia el hospital?","¿Cómo nos comunicamos con la familia durante el parto?"]},
{w:37,cm:48.6,g:2900,cmp:"una acelga",
 bebe:["Embarazo a término temprano: si nace ahora, está preparado.","Practica respirar, chupar y agarrar.","Sigue ganando grasa para regular la temperatura."],
 ella:"Puedes expulsar el tapón mucoso o notar contracciones más frecuentes. Si rompes aguas o las contracciones son regulares, consulta.",
 pareja:"Ten el bolso en la puerta y el depósito del coche lleno. Deja el trabajo organizado para poder irte en cualquier momento.",
 hitos:"Embarazo a término (semana 37). Consulta semanal.",
 temas:["¿Estamos listos para salir en cualquier momento?","¿Cómo queremos las primeras horas con el bebé?"]},
{w:38,cm:49.8,g:3100,cmp:"un puerro",
 bebe:["Sus órganos están listos para funcionar fuera.","Su agarre es fuerte.","Puede nacer cualquier día."],
 ella:"Puedes sentirte impaciente y con molestias en la pelvis. Es normal alternar ganas de que llegue y miedo.",
 pareja:"Ten el teléfono cargado y el bolso preparado. Sabe dónde están la documentación, la silla del coche y las llaves.",
 hitos:"Consulta semanal. Monitorización fetal en algunos protocolos.",
 temas:["¿Qué hacemos con el tiempo que queda?","¿Quién quiere ella que esté presente en el parto?"]},
{w:39,cm:50.7,g:3300,cmp:"una sandía pequeña",
 bebe:["Su cerebro sigue creciendo y lo hará durante años.","Su piel es más gruesa y rosada.","Está colocado para nacer."],
 ella:"Es posible que estés cansada de esperar. Descansa, camina si te apetece y pide lo que necesites.",
 pareja:"Esta semana tu trabajo es estar disponible. Cancela lo que no sea imprescindible y ocúpate de las tareas para que ella descanse.",
 hitos:"Consulta semanal. Monitorización.",
 temas:["¿Qué queremos hacer los últimos días solos?","¿Cómo queremos contar que nació?"]},
{w:40,cm:51.2,g:3450,cmp:"una sandía",
 bebe:["Fecha probable de parto. Solo una pequeña parte de los bebés nace exactamente este día.","Está completamente formado y listo.","Puede nacer hoy o dentro de dos semanas; ambas cosas son normales."],
 ella:"Si el parto no empieza, el equipo médico irá controlando al bebé con más frecuencia. Pasarse de la fecha es habitual.",
 pareja:"Mantén la calma y el plan a mano. Evita preguntar a cada rato 'si ya viene': ella lo sabrá antes que nadie.",
 hitos:"Fecha probable de parto. Monitorización cada pocos días si se pasa.",
 temas:["¿Cómo llevamos la espera?","¿Qué queremos hacer si proponen inducir el parto?"]},
{w:41,cm:51.5,g:3600,cmp:"una sandía",
 bebe:["Sigue creciendo y acumulando grasa.","El líquido amniótico puede empezar a disminuir; por eso los controles.","Está listo desde hace semanas."],
 ella:"Los controles se hacen más frecuentes. Es normal sentirse muy cansada e impaciente. Consulta si notas menos movimientos.",
 pareja:"Acompaña a todos los controles. Prepárate para que propongan una inducción y hablen antes de qué quieren decidir.",
 hitos:"Monitorización cada 48–72 horas. Se suele proponer inducción entre la semana 41 y la 42.",
 temas:["¿Qué opinamos sobre la inducción?","¿Cómo nos cuidamos mutuamente mientras esperamos?"]},
{w:42,cm:51.7,g:3700,cmp:"una sandía",
 bebe:["Embarazo prolongado. El equipo médico va a proponer que nazca ya.","Está listo para respirar, comer y mirarte."],
 ella:"A partir de aquí lo habitual es inducir el parto o programar una cesárea. Tu equipo te explicará las opciones.",
 pareja:"Estén juntos en cada decisión. Ya casi lo tienen en brazos.",
 hitos:"Inducción o cesárea programada.",
 temas:["¿Cómo queremos que sea el primer día en casa?"]}
];

// ====== HITOS POR DEFECTO (semana + día en que suelen ocurrir) ======
const HITOS_BASE = [
 {key:"test", w:4, d:3, title:"Test de embarazo positivo", desc:"El día que lo supimos.", emocional:true},
 {key:"consulta1", w:7, d:0, title:"Primera consulta prenatal", desc:"Historia clínica, analítica inicial y planificación del seguimiento."},
 {key:"eco1", w:8, d:0, title:"Primera ecografía", desc:"Primera imagen. Se mide el embrión y se confirma la fecha probable de parto."},
 {key:"intrauterino", w:8, d:0, title:"Embarazo intrauterino confirmado", desc:"El embrión está bien ubicado en el útero."},
 {key:"latido", w:8, d:0, title:"Actividad cardíaca detectada", desc:"El corazón ya late. Un momento que muchos recuerdan para siempre.", emocional:true},
 {key:"nipt", w:10, d:0, title:"NIPT", desc:"Test prenatal no invasivo: análisis de sangre para cribado de alteraciones cromosómicas."},
 {key:"eco12", w:12, d:0, title:"Ecografía del primer trimestre", desc:"Translucencia nucal y anatomía temprana. Suele ser la primera ecografía 'de verdad'."},
 {key:"sexo", w:16, d:0, title:"Descubrimos el sexo", desc:"Si quieren saberlo, puede confirmarse por NIPT o en la ecografía.", emocional:true},
 {key:"movimientos", w:19, d:0, title:"Primeros movimientos", desc:"Como burbujas o mariposas. Cada embarazo es distinto.", emocional:true},
 {key:"eco20", w:20, d:0, title:"Ecografía morfológica", desc:"Revisión detallada de órganos, placenta y crecimiento."},
 {key:"patada", w:23, d:0, title:"Pareja sintió la primera patada", desc:"La primera vez que lo sentimos los dos.", emocional:true},
 {key:"t3", w:28, d:0, title:"Inicio del tercer trimestre", desc:"Última etapa. Controles más frecuentes y preparación práctica."},
 {key:"bolso", w:34, d:0, title:"Preparación del bolso", desc:"Ropa, documentación, cargadores. Listo en la puerta."},
 {key:"termino", w:37, d:0, title:"Embarazo a término", desc:"Desde ahora puede nacer en cualquier momento."},
 {key:"fpp", w:40, d:0, title:"Fecha probable de parto", desc:"Una referencia, no una cita. Pocos bebés nacen justo este día."},
 {key:"nacimiento", w:40, d:0, title:"Nacimiento", desc:"El primer capítulo de la historia de después.", emocional:true}
];

const HITOS_SUGERIDOS = ["Se lo contamos a los abuelos","Se lo contamos a los hermanos","Se lo contamos a los primos","Compramos la primera ropa","Elegimos el nombre","Preparamos su habitación","Primer regalo para el bebé","Primera vez que vimos su cara en una eco"];

// ====== PAÍSES: terminología, formato y emergencias ======
const PAISES = {
 ES:{nombre:"España", locale:"es-ES", matrona:"matrona", gine:"ginecóloga/o", analisis:"analítica", emergencias:"112", turno:"cita", coche:"coche", cochecito:"carrito"},
 UY:{nombre:"Uruguay", locale:"es-UY", matrona:"partera", gine:"ginecóloga/o", analisis:"análisis", emergencias:"911", turno:"consulta", coche:"auto", cochecito:"cochecito"},
 AR:{nombre:"Argentina", locale:"es-AR", matrona:"obstétrica", gine:"obstetra", analisis:"análisis", emergencias:"107", turno:"turno", coche:"auto", cochecito:"cochecito"},
 MX:{nombre:"México", locale:"es-MX", matrona:"partera", gine:"ginecóloga/o", analisis:"análisis", emergencias:"911", turno:"cita", coche:"coche", cochecito:"carriola"},
 CO:{nombre:"Colombia", locale:"es-CO", matrona:"partera", gine:"ginecóloga/o", analisis:"exámenes", emergencias:"123", turno:"cita", coche:"carro", cochecito:"coche"},
 CL:{nombre:"Chile", locale:"es-CL", matrona:"matrona", gine:"ginecóloga/o", analisis:"exámenes", emergencias:"131", turno:"hora", coche:"auto", cochecito:"coche"},
 PE:{nombre:"Perú", locale:"es-PE", matrona:"obstetra", gine:"ginecóloga/o", analisis:"análisis", emergencias:"116", turno:"cita", coche:"carro", cochecito:"coche"},
 OT:{nombre:"Otro país", locale:"es", matrona:"matrona o partera", gine:"ginecóloga/o", analisis:"análisis", emergencias:"el número de emergencias local", turno:"cita", coche:"coche", cochecito:"cochecito"}
};

// ====== SÍNTOMAS ======
const SINTOMAS = [
 {k:"nauseas",l:"Náuseas"},{k:"cansancio",l:"Cansancio"},{k:"pechos",l:"Sensibilidad en pechos"},{k:"cabeza",l:"Dolor de cabeza"},
 {k:"colicos",l:"Cólicos"},{k:"animo",l:"Estado de ánimo bajo"},{k:"sueno",l:"Problemas de sueño"},{k:"apetito",l:"Cambios de apetito"},{k:"mareos",l:"Mareos"}
];
const ESCALA = ["Nada","Leve","Moderado","Intenso"];

// ====== SEÑALES DE ALARMA (detección en el asistente) ======
const ALARMA = [
 {re:/sangr(ado|o|ando)\s*(abundante|mucho|fuerte|rojo)|hemorragia|mucha sangre/i, l:"sangrado abundante"},
 {re:/dolor\s*(abdominal|de\s*barriga|de\s*vientre|de\s*panza)?\s*(muy\s*)?(intenso|fuerte|insoportable|agudo)|dolor (muy )?fuerte/i, l:"dolor abdominal intenso"},
 {re:/(un\s*lado|unilateral|lado\s*(derecho|izquierdo))/i, l:"dolor fuerte en un lado"},
 {re:/desmay|me\s*desvanec|perd[ií]\s*el\s*conocimiento/i, l:"desmayo"},
 {re:/(dolor\s*de\s*cabeza|cefalea|jaqueca).*(visi[oó]n|ver\s*borroso|luces|manchas|destellos)|(visi[oó]n|borroso|destellos).*(dolor\s*de\s*cabeza|cefalea)/i, l:"dolor de cabeza intenso con alteraciones visuales"},
 {re:/(dificultad|cuesta|no\s*puedo)\s*(para\s*)?respirar|falta\s*de\s*aire|ahog/i, l:"dificultad para respirar"},
 {re:/fiebre\s*(alta|de\s*(38|39|40))|39\s*grados|40\s*grados/i, l:"fiebre alta"},
 {re:/(romp[ií]|rotura|perd[ií]|p[eé]rdida)\s*(de\s*)?(aguas|l[ií]quido)|bolsa\s*rota/i, l:"posible rotura de bolsa"},
 {re:/(no\s*(lo\s*)?siento|no\s*se\s*mueve|menos\s*movimientos|dej[oó]\s*de\s*mover)/i, l:"disminución de movimientos"},
 {re:/convulsi/i, l:"convulsión"}
];
